### ISSUE TITLE
Getting error when execute with sudo 

### ISSUE THREAD

**Issue by jairajsahgal** [mrjoker05/ImSleepy#3]
File "CronSet.py", line 35
    command = f" {user} cd ~/ImSleepy python3 ImSleepy.py bg {course} {duration} "
                                                                                 ^
SyntaxError: invalid syntax

Getting this error when executing with cmd : "sudo python CronSet.py"

**Comment by ev1lm0rty** [comment]
Iam currently changing the cronset.py to be more user friendly, and will change this too. Thanks for raising this issue, will look into it.
